In [1]:
import pandas as pd
import time

In [2]:
import numpy as np
import matplotlib.ticker as mtick
import matplotlib.pyplot as plt

In [55]:
hcpcs = 'PE_TownHall_HCPCS_level.xls'
hcpcs2 = 'HCPC2018_CONTR_ANWEB_disc.xlsx'
dxcs = 'DXCCSR_v2022-1.CSV'

In [56]:
hcpcs1 = pd.read_excel(hcpcs)
hcpcs2 = pd.read_excel(hcpcs2)

In [ ]:
x1 = hcpcs1[['HCPCS', 'Desc']]
x1['cat'] = pd.NA

In [58]:
x2 = hcpcs2[['HCPC', 'LONG DESCRIPTION']].rename(columns={'LONG DESCRIPTION':'Desc', 'HCPC':'HCPCS'})
x2['cat'] = "HCPC"

In [59]:
hcpcs = pd.concat([x1, x2])

In [60]:
dxcs = pd.read_csv(dxcs)

In [61]:
dxcs.columns = [x.replace("'", "") for x in dxcs.columns.tolist()]

In [62]:
dxcs = dxcs.applymap(lambda x: x.replace('\'', ''))

In [63]:
dxcs = dxcs[['ICD-10-CM CODE', 'ICD-10-CM CODE DESCRIPTION', 'Default CCSR CATEGORY OP', 'Default CCSR CATEGORY DESCRIPTION OP']].rename(columns={'ICD-10-CM CODE':'CODE', 'ICD-10-CM CODE DESCRIPTION':'DESCRIPTION', 'Default CCSR CATEGORY OP':'CATEGORY', 'Default CCSR CATEGORY DESCRIPTION OP':'CATEGORY DESCRIPTION'})

In [17]:
hcpcs.head(10)

   HCPCS                          Desc  cat
0  99213  Office/outpatient visit, est  NaN
1  99214  Office/outpatient visit, est  NaN
2  78465    Heart image (3d), multiple  NaN
3  99232      Subsequent hospital care  NaN
4  66984  Cataract surg w/iol, 1 stage  NaN
5  92014          Eye exam & treatment  NaN
6  99212  Office/outpatient visit, est  NaN
7  77418   Radiation tx delivery, imrt  NaN
8  93307            Echo exam of heart  NaN
9  88305    Tissue exam by pathologist  NaN

In [64]:
dxcs.head(10)

,CODE,DESCRIPTION,CATEGORY,CATEGORY DESCRIPTION
0,A000,"Cholera due to Vibrio cholerae 01, biovar chol...",DIG001,Intestinal infection
1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor",DIG001,Intestinal infection
2,A009,"Cholera, unspecified",DIG001,Intestinal infection
3,A0100,"Typhoid fever, unspecified",DIG001,Intestinal infection
4,A0101,Typhoid meningitis,NVS001,Meningitis
5,A0102,Typhoid fever with heart involvement,INF003,Bacterial infections
6,A0103,Typhoid pneumonia,RSP002,Pneumonia (except that caused by tuberculosis)
7,A0104,Typhoid arthritis,MUS001,Infective arthritis
8,A0105,Typhoid osteomyelitis,MUS002,Osteomyelitis
9,A0109,Typhoid fever with other complications,DIG001,Intestinal infection

In [14]:
hcpcs.to_excel('PROCS.xlsx', index=False)
dxcs.to_excel('DXS.xlsx', index=False)

In [18]:
reffile = 'C:/path/to/image/DXCCSR_v2022-1/DXCCSR-Reference-File-v2022-1.xlsx'

In [20]:
ref = pd.read_excel(reffile, sheet_name='Naming_Conventions', skiprows=1)

In [21]:
ref

                          ICD-10-CM Diagnosis Chapter 3-Character Abbreviation
0           Certain Infectious and Parasitic Diseases                      INF
1                                           Neoplasms                      NEO
2   Diseases of the Blood and Blood Forming Organs...                      BLD
3       Endocrine, Nutritional and Metabolic Diseases                      END
4   Mental, Behavioral and Neurodevelopmental Diso...                      MBD
5                      Diseases of the Nervous System                      NVS
6                      Diseases of the Eye and Adnexa                      EYE
7             Diseases of the Ear and Mastoid Process                      EAR
8                  Diseases of the Circulatory System                      CIR
9                  Diseases of the Respiratory System                      RSP
10                   Diseases of the Digestive System                      DIG
11       Diseases of the Skin and Subcutaneous Tissue                      SKN
12  Diseases of the Musculoskeletal System and Con...                      MUS
13               Diseases of the Genitourinary System                      GEN
14           Pregnancy, Childbirth and the Puerperium                      PRG
15  Certain Conditions Originating in the Perinata...                      PNL
16  Congenital Malformations, Deformations and Chr...                      MAL
17  Symptoms, Signs and Abnormal Clinical and Labo...                      SYM
18  Injury, Poisoning and Certain Other Consequenc...                      INJ
19                       External Causes of Morbidity                      EXT
20  Factors Influencing Health Status and Contact ...                      FAC
21  Unacceptable principal diagnosis (inpatient da...                      XXX

In [73]:
dxcs

,CODE,DESCRIPTION,CATEGORY,CATEGORY DESCRIPTION,3-Character Abbreviation,cat
0,A000,"Cholera due to Vibrio cholerae 01, biovar chol...",DIG001,Intestinal infection,DIG,Diseases of the Digestive System
1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor",DIG001,Intestinal infection,DIG,Diseases of the Digestive System
2,A009,"Cholera, unspecified",DIG001,Intestinal infection,DIG,Diseases of the Digestive System
3,A0100,"Typhoid fever, unspecified",DIG001,Intestinal infection,DIG,Diseases of the Digestive System
4,A0101,Typhoid meningitis,NVS001,Meningitis,NVS,Diseases of the Nervous System
...,...,...,...,...,...,...
73365,Z9912,Encounter for respirator [ventilator] dependen...,FAC012,Other specified encounters and counseling,FAC,Factors Influencing Health Status and Contact ...
73366,Z992,Dependence on renal dialysis,FAC025,Other specified status,FAC,Factors Influencing Health Status and Contact ...
73367,Z993,Dependence on wheelchair,FAC025,Other specified status,FAC,Factors Influencing Health Status and Contact ...
73368,Z9981,Dependence on supplemental oxygen,FAC025,Other specified status,FAC,Factors Influencing Health Status and Contact ...
73369,Z9989,Dependence on other enabling machines and devices,FAC025,Other specified status,FAC,Factors Influencing Health Status and Contact ...

In [66]:
dxcs['3-Character Abbreviation'] = dxcs.CATEGORY.apply(lambda x:  [ abbr for abbr in ref['3-Character Abbreviation'].to_list() if abbr in x][0] )

In [72]:
dxcs['cat'] = dxcs['3-Character Abbreviation'].apply(lambda x: ref.loc[ref['3-Character Abbreviation'] == x, 'ICD-10-CM Diagnosis Chapter'].to_list()[0])

In [74]:
dxcs.to_excel('DXS.xlsx', index=False)

In [22]:
import re

In [148]:
import pandas as pd
place_of_service_codes = pd.read_excel('place_of_service_codes.xls')
modifier_codes = pd.read_excel('modifier_codes.xls')

In [6]:
modifier_codes = modifier_codes.loc[~pd.isna(modifier_codes['HCPCS Modifiers']), ]

In [10]:
modifier_codes = modifier_codes.loc[~pd.isna(modifier_codes['Modifiers Description']), ]

In [17]:
modifier_codes['cat_desc'] = modifier_codes['HCPCS Modifiers'].apply(lambda x: x[:1])

In [18]:
modifier_codes

,HCPCS Modifiers,Modifiers Description,cat_desc
0,A1,Dressing for 1 wound,A
1,A2,Dressing for 2 wounds,A
2,A3,Dressing for 3 wounds,A
3,A4,Dressing for 4 wounds,A
4,A5,Dressing for 5 wounds,A
...,...,...,...
415,XS,"Separate structure, a service that is distinct...",X
416,XU,"Unusual non-overlapping service, the use of a ...",X
419,ZA,Novartis/sandoz (Terminated on 03/31/2018),Z
420,ZB,Pfizer/hospira (Terminated on 03/31/2018),Z
421,ZC,Merck/samsung bioepis (Terminated on 03/31/2018),Z

In [65]:
# re.sub()
re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\2', '82-98')

'98'

In [129]:

y = list(set([re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\2', '82-98'), re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\2', '82-98')]))
x = list(set([re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\1', '82-98'), re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\2', '82-98')]))

In [131]:
x.sort()

In [117]:
for ind in range(1, 11, 1):
        print(ind)

1
2
3
4
5
6
7
8
9
10

In [149]:
def get_codelist(x):
    b = []
    x.sort()
    if len(x) == 2:
        for ind in range(int(x[0]), int(x[1])+1, 1):
            b.append(ind)
        
        return b
    else:
        return x

In [137]:
get_codelist(y)

['98']

In [70]:
list(set([re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\1', '82-98'), re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\1', '82-98')]))

['82']

In [59]:
re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\1', '98')

'98'

In [150]:
place_of_service_codes['Place of Service Code(s)'].apply(lambda x: get_codelist(list(set([re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\1', str(x)), re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\2', str(x))]))))

0                                                   [1]
1                                                   [2]
2                                                   [3]
3                                                   [4]
4                                                   [5]
5                                                   [6]
6                                                   [7]
7                                                   [8]
8                                                   [9]
9                                                  [10]
10                                                 [11]
11                                                 [12]
12                                                 [13]
13                                                 [14]
14                                                 [15]
15                                                 [16]
16                                                 [17]
17                                                 [18]
18                                                 [19]
19                                                 [20]
20                                                 [21]
21                                                 [22]
22                                                 [23]
23                                                 [24]
24                                                 [25]
25                                                 [26]
26                                     [27, 28, 29, 30]
27                                                 [31]
28                                                 [32]
29                                                 [33]
30                                                 [34]
31                             [35, 36, 37, 38, 39, 40]
32                                                 [41]
33                                                 [42]
34                             [43, 44, 45, 46, 47, 48]
35                                                 [49]
36                                                 [50]
37                                                 [51]
38                                                 [52]
39                                                 [53]
40                                                 [54]
41                                                 [55]
42                                                 [56]
43                                                 [57]
44                                                 [58]
45                                                 [59]
46                                                 [60]
47                                                 [61]
48                                                 [62]
49                                             [63, 64]
50                                                 [65]
51                                 [66, 67, 68, 69, 70]
52                                                 [71]
53                                                 [72]
54                     [73, 74, 75, 76, 77, 78, 79, 80]
55                                                 [81]
56    [82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 9...
57                                                 [99]
Name: Place of Service Code(s), dtype: object

In [151]:
place_of_service_codes['Place of Service Code(s)'] = place_of_service_codes['Place of Service Code(s)'].apply(lambda x: get_codelist(list(set([re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\1', str(x)), re.sub(r'([0-9]{2})[-]([0-9]{2})', r'\2', str(x))]))))

In [152]:
place_of_service_codes = place_of_service_codes.explode(['Place of Service Code(s)'])

In [153]:
place_of_service_codes['Place of Service Code(s)'] = place_of_service_codes['Place of Service Code(s)'].astype(int)

In [154]:
place_of_service_codes.sort_values(by=['Place of Service Code(s)'], inplace=True)

In [158]:
place_of_service_codes.fillna('Unassigned', inplace=True)

In [160]:
place_of_service_codes

,Place of Service Code(s),Place of Service Name,Place of Service Description
0,1,Pharmacy **,A facility or location where drugs and other m...
1,2,Telehealth Provided Other than in Patient’s Home,The location where health services and health ...
2,3,School,A facility whose primary purpose is education....
3,4,Homeless Shelter,A facility or location whose primary purpose i...
4,5,Indian Health Service\nFree-standing Facility,"A facility or location, owned and operated by ..."
...,...,...,...
56,95,Unassigned,Unassigned
56,96,Unassigned,Unassigned
56,97,Unassigned,Unassigned
56,98,Unassigned,Unassigned
57,99,Other Place of Service,Other place of service not identified above.

In [159]:
modifier_codes

,HCPCS Modifiers,Modifiers Description,cat_desc
0,A1,Dressing for 1 wound,A
1,A2,Dressing for 2 wounds,A
2,A3,Dressing for 3 wounds,A
3,A4,Dressing for 4 wounds,A
4,A5,Dressing for 5 wounds,A
...,...,...,...
415,XS,"Separate structure, a service that is distinct...",X
416,XU,"Unusual non-overlapping service, the use of a ...",X
419,ZA,Novartis/sandoz (Terminated on 03/31/2018),Z
420,ZB,Pfizer/hospira (Terminated on 03/31/2018),Z
421,ZC,Merck/samsung bioepis (Terminated on 03/31/2018),Z

In [162]:
place_of_service_codes.to_excel('place_of_service_codes.xlsx', index=False)
modifier_codes.to_excel('modifier_codes.xlsx', index=False)